<?php

// $Id: mauikeywordextractor.module,v 1.6 2010/05/09 19:55:26 tomdude48 Exp $

/**
 * @file
 * An example content analyzer using the Content Analysis API
 */
function mauikeywordextractor_menu() {
  $items = array();

  $items['admin/settings/mauikeywordextractor'] = array(
    'title' => 'Search engine terms',
    'description' => 'Get keywords from search engines.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mauikeywordextractor_admin_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('admin content analysis'),
    'type' => MENU_NORMAL_ITEM,
      //'file' => 'mauikeywordextractor.admin.inc',
  );


  return $items;
}

/**
 *  Implentation of hook_contentanalysis_analyzers()
 *  register contentanalysisexample with contentanalysis analyzers registry
 */
function mauikeywordextractor_contentanalysis_analyzers() {
  $analyzers['mauikeywordextractor'] = array(
    'title' => t('MAUI Keyword Extractor'),
    'module' => 'mauikeywordextractor',
    'callback' => 'mauikeywordextractor_analyzer',
    //'form elements callback' => 'mauikeywordextractor_analyzer_form_elements',
    //'node form submit callback' => 'mauikeywordextractor_node_form_submit',
    'weight' => -5,
  );
  return $analyzers;
}




/**
 * Implementation of hook_analyzer() via custom define callback
 * 
 * Performs the analysis. 
 * callback is defined in hook_contentanalysis_analyzers ['callback']
 * 
 * @param unknown_type $context
 *   Array context format defined by contentanalysis.module
 * @param unknown_type $analysis
 *  Array analysis format defined by contentanalysis.module
 * @param unknown_type $params
 *   Array customer defined paramters
 */
function mauikeywordextractor_analyzer($context, $analysis, $params) {


// call maui implementation with the parameters $context['body']

 
  
  $terms = mauikeywordextractor_autokeyword($context, $analysis);
 

  $rows = array();
  $header1 = array(
    array('data' => t('Term')),
   //array('data' => t('Relevance')),
  );
  if (is_array($terms)) {
    foreach ($terms as $v) {
      $rows[] = array(
        "<span class=\"kwresearch_keyword\">" . $v . "</span>"
      //  "<span class=\"rules_autotag\">" . $v . "</span>"
      );
    }
  }
  if (!$rows) {
    $rows[] = array(array(
        'data' => t('No keywords available.'),
        'colspan' => count($header),
    ));
  }



  $out = theme('table', array('header' => $header, 'rows' => $rows));

  $analysis['content'][] = contentanalysis_format_content($out, -1);

  // send out content into a text file 

  if (isset($_POST['analyzers'])) {
    $content = $_POST['body'];
    $file = fopen("/var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/data/automatic_tagging/train/merge/content.txt", "w");
    fwrite($file, $content);
    fclose($file);
    //  print_r(error_get_last());
  }

  return $analysis;
}

/**
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function mauikeywordextractor_autokeyword($context, &$analysis = NULL) {
  /*
   * Run maui from drupal
   * 
   */
// $file = fopen("/var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/data/automatic_tagging/train/merge/content.key", "w");
//    //fwrite($file, $text);
   
// 
// fclose($file);
//exec("cd /var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/ && touch /tmp/testfile.txt && java -cp /var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/bin:/var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/lib/*  maui.main.MauiModelBuilder -l /var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/data/automatic_tagging/train/merge/ -m test -v none");
exec("cd /var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/ && touch /tmp/testfile.txt && java -cp /var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/bin:/var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/lib/*  maui.main.MauiTopicExtractor -l /var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/data/automatic_tagging/train/merge/ -m test -v none");

//$filename = "/var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/data/automatic_tagging/train/merge/content.key";
//unlink($filename);

  // get te file content into drupal
  $filename = "/var/www/dru7/sites/all/modules/contentanalysis/Maui1.2/data/automatic_tagging/train/merge/content.key";
  file_get_contents($filename);
  $terms = array();
  $handle = fopen($filename, "r"); // handle input files ,reading input file
 $vid = taxonomy_vocabulary_machine_name_load('tags')->vid;
  while ($line = fgets($handle)) {
  taxonomy_term_save((object) array(
 'name' => $line,
 'vid' => $vid,
));
 array_push($terms, $line); 
    }
    
  
  
  fclose($handle);
  unlink($filename);

  
 /*
  * create a vocabulary  see website
  * save vocab. to db
  * load it from db --> so that you can get its new id
  * 
  * for each term in $terms>
  * create a term with term as $name and id of vocab. that you just created
  * -save the term
   *  */
 //module_load_include('inc', 'rules', 'rules_autotag.module');
  //$mauikeywordextractor=  rules_autotag_extract($terms, $terms);
  
 //$mauikeywordextractor= rules_autotag_exact_match($terms,$vocabulary);// I tried to pass same terms as text and vocabulary 
  
  //$terms1= rules_autotag_exact_match($terms,$terms);// I tried to pass same terms as text and vocabulary 
  
  return $terms;
}




